from django.contrib import admin

from .models import Property, Reservation

# allows to display database content in the admin page generated by Django
admin.site.register(Property)
admin.site.register(Reservation)


# instead of showing the values as objects it make it show them as a table with the following contents
class ReservationAdmin(admin.ModelAdmin):
    list_display = ("property_name", "start_date", "end_date")
